ALTER TABLE public.vendas
    ADD COLUMN IF NOT EXISTS cliente_cpf text,
    ADD COLUMN IF NOT EXISTS desconto numeric(12, 2) NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS public.movimentos_caixa (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id uuid NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
    caixa_id uuid NOT NULL REFERENCES public.caixas(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES auth.users(id),
    tipo text NOT NULL CHECK (tipo IN ('sangria', 'suprimento')),
    valor numeric(12, 2) NOT NULL CHECK (valor > 0),
    motivo text NOT NULL CHECK (length(trim(motivo)) > 0),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS movimentos_caixa_empresa_caixa_idx
    ON public.movimentos_caixa (empresa_id, caixa_id, created_at);

ALTER TABLE public.movimentos_caixa ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS movimentos_caixa_select_empresa ON public.movimentos_caixa;
CREATE POLICY movimentos_caixa_select_empresa
    ON public.movimentos_caixa
    FOR SELECT
    TO authenticated
    USING (
        user_id = auth.uid()
        AND EXISTS (
            SELECT 1
            FROM public.usuarios_empresas ue
            WHERE ue.user_id = auth.uid()
              AND ue.empresa_id = movimentos_caixa.empresa_id
        )
    );

DROP POLICY IF EXISTS movimentos_caixa_insert_empresa ON public.movimentos_caixa;
CREATE POLICY movimentos_caixa_insert_empresa
    ON public.movimentos_caixa
    FOR INSERT
    TO authenticated
    WITH CHECK (
        user_id = auth.uid()
        AND EXISTS (
            SELECT 1
            FROM public.usuarios_empresas ue
            WHERE ue.user_id = auth.uid()
              AND ue.empresa_id = movimentos_caixa.empresa_id
        )
        AND EXISTS (
            SELECT 1
            FROM public.caixas c
            WHERE c.id = movimentos_caixa.caixa_id
              AND c.empresa_id = movimentos_caixa.empresa_id
              AND c.user_id = auth.uid()
        )
    );

GRANT SELECT, INSERT ON public.movimentos_caixa TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.movimentos_caixa_id_seq TO authenticated;
